using System.Collections.Concurrent;
using System.Security.Cryptography;
using System.Text;
using ImageCleanup.Core.Thumbnails;

namespace ImageCleanup.Data.Services;

/// <summary>
/// Get-or-generate disk cache for preview thumbnails. Thumbnails are stored as
/// loose PNG files under the cache directory rather than as SQLite BLOBs, so
/// FileRecords stays lightweight and the cache can be cleared by deleting a
/// folder. Keyed by file path + LastModified so a changed source file is
/// regenerated rather than served stale.
/// </summary>
public sealed class ThumbnailCache
{
    // Static and keyed by absolute cache file path (not per-instance): the App
    // layer creates a separate ThumbnailCache per feature ViewModel
    // (Duplicates, Quality), but they all point at the same physical cache
    // directory by default, so races can happen across instances too, not
    // just within one. A per-key lock means the second concurrent request for
    // the same thumbnail waits for the first to finish and reads its result,
    // instead of both racing to write (or read mid-write) the same file —
    // that race is what caused the "file in use by another process"
    // IOException once recursive scanning started requesting far more
    // thumbnails concurrently.
    private static readonly ConcurrentDictionary<string, SemaphoreSlim> KeyLocks = new(StringComparer.OrdinalIgnoreCase);

    private readonly string _cacheDirectory;

    public ThumbnailCache(string? cacheDirectory = null)
    {
        _cacheDirectory = cacheDirectory ?? Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "ImageCleanup", "thumbnails");
        Directory.CreateDirectory(_cacheDirectory);
    }

    /// <summary>
    /// Returns cached thumbnail bytes for <paramref name="filePath"/> if present,
    /// otherwise generates, caches, and returns them. Returns null if the source
    /// file cannot be decoded, or if the cache read/write hits an I/O error
    /// (e.g. a transient sharing violation) — a missing thumbnail for one file
    /// should never crash the whole scan.
    /// </summary>
    public byte[]? GetOrCreateThumbnail(string filePath, DateTime lastModified, int maxDimension = 128)
    {
        var cachePath = GetCachePath(filePath, lastModified, maxDimension);

        // Fast path: already cached. If this races with another thread's
        // in-progress write, TryReadCache treats the IOException as a miss
        // and we fall through to the locked path below instead of throwing.
        if (TryReadCache(cachePath, out var cached))
            return cached;

        var keyLock = KeyLocks.GetOrAdd(cachePath, static _ => new SemaphoreSlim(1, 1));
        keyLock.Wait();
        try
        {
            // Re-check: another thread may have generated it while we waited.
            if (TryReadCache(cachePath, out cached))
                return cached;

            byte[]? bytes;
            try
            {
                bytes = ThumbnailGenerator.GenerateThumbnail(filePath, maxDimension);
            }
            catch (IOException)
            {
                // Source file transiently locked/unreadable — no thumbnail this time.
                return null;
            }

            if (bytes is not null)
                WriteCacheAtomically(cachePath, bytes);

            return bytes;
        }
        finally
        {
            keyLock.Release();
        }
    }

    private static bool TryReadCache(string cachePath, out byte[]? bytes)
    {
        bytes = null;
        if (!File.Exists(cachePath)) return false;

        try
        {
            bytes = File.ReadAllBytes(cachePath);
            return true;
        }
        catch (IOException)
        {
            // Being written concurrently (or transiently locked, e.g. by an
            // antivirus scan) — treat as a cache miss rather than throwing.
            return false;
        }
    }

    /// <summary>
    /// Writes to a temp file in the same directory, then renames it into place.
    /// Defense in depth alongside the per-key lock: even under the lock, this
    /// keeps the window where another reader could observe a partially-written
    /// or momentarily-locked target file as small as a single rename instead
    /// of the whole write.
    /// </summary>
    private static void WriteCacheAtomically(string cachePath, byte[] bytes)
    {
        var tempPath = $"{cachePath}.{Guid.NewGuid():N}.tmp";
        try
        {
            File.WriteAllBytes(tempPath, bytes);
            File.Move(tempPath, cachePath, overwrite: true);
        }
        catch (IOException)
        {
            // Best-effort: a failed cache write should never crash the scan —
            // the caller still has the freshly generated bytes in memory even
            // if we couldn't persist them this time.
            try { if (File.Exists(tempPath)) File.Delete(tempPath); }
            catch (IOException) { /* best-effort cleanup only */ }
        }
    }

    private string GetCachePath(string filePath, DateTime lastModified, int maxDimension)
    {
        var key = ComputeKey(filePath, lastModified, maxDimension);
        return Path.Combine(_cacheDirectory, $"{key}.png");
    }

    private static string ComputeKey(string filePath, DateTime lastModified, int maxDimension)
    {
        var input = $"{filePath.ToLowerInvariant()}|{lastModified.Ticks}|{maxDimension}";
        var hash  = SHA256.HashData(Encoding.UTF8.GetBytes(input));
        return Convert.ToHexString(hash);
    }
}
